### PR TITLE
Add favicon

### PR DESCRIPTION
**Pull request by mychaelgo**
@PXgamer  please review for issue #3 👍

### CODE REVIEW

**Comment by owenvoke** [comment]
Cheers for that 😄 I'll close issue #3

**Comment by owenvoke** [comment]
@mychaelgo you don't happen to have that in a slightly larger size do you? (Just to add to the README)

**Comment by mychaelgo** [comment]
@PXgamer sure, can you create another issue? :dancing_men:

**Comment by owenvoke** [comment]
@mychaelgo done. #5

**Pull request merged**
